/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEvaluateRouteImport } from './routes/_authenticated/evaluate'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedExamCompetitionIdRouteImport } from './routes/_authenticated/exam.$competitionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvaluateRoute = AuthenticatedEvaluateRouteImport.update({
  id: '/evaluate',
  path: '/evaluate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamCompetitionIdRoute =
  AuthenticatedExamCompetitionIdRouteImport.update({
    id: '/exam/$competitionId',
    path: '/exam/$competitionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/rules': typeof RulesRoute
  '/verify': typeof VerifyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evaluate': typeof AuthenticatedEvaluateRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/exam/$competitionId': typeof AuthenticatedExamCompetitionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/rules': typeof RulesRoute
  '/verify': typeof VerifyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evaluate': typeof AuthenticatedEvaluateRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/exam/$competitionId': typeof AuthenticatedExamCompetitionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/rules': typeof RulesRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/evaluate': typeof AuthenticatedEvaluateRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/exam/$competitionId': typeof AuthenticatedExamCompetitionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/events'
    | '/faq'
    | '/leaderboard'
    | '/privacy'
    | '/results'
    | '/rules'
    | '/verify'
    | '/dashboard'
    | '/evaluate'
    | '/profile'
    | '/exam/$competitionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/events'
    | '/faq'
    | '/leaderboard'
    | '/privacy'
    | '/results'
    | '/rules'
    | '/verify'
    | '/dashboard'
    | '/evaluate'
    | '/profile'
    | '/exam/$competitionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/events'
    | '/faq'
    | '/leaderboard'
    | '/privacy'
    | '/results'
    | '/rules'
    | '/verify'
    | '/_authenticated/dashboard'
    | '/_authenticated/evaluate'
    | '/_authenticated/profile'
    | '/_authenticated/exam/$competitionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PrivacyRoute: typeof PrivacyRoute
  ResultsRoute: typeof ResultsRoute
  RulesRoute: typeof RulesRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evaluate': {
      id: '/_authenticated/evaluate'
      path: '/evaluate'
      fullPath: '/evaluate'
      preLoaderRoute: typeof AuthenticatedEvaluateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam/$competitionId': {
      id: '/_authenticated/exam/$competitionId'
      path: '/exam/$competitionId'
      fullPath: '/exam/$competitionId'
      preLoaderRoute: typeof AuthenticatedExamCompetitionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEvaluateRoute: typeof AuthenticatedEvaluateRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedExamCompetitionIdRoute: typeof AuthenticatedExamCompetitionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEvaluateRoute: AuthenticatedEvaluateRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedExamCompetitionIdRoute: AuthenticatedExamCompetitionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  LeaderboardRoute: LeaderboardRoute,
  PrivacyRoute: PrivacyRoute,
  ResultsRoute: ResultsRoute,
  RulesRoute: RulesRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
